config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  # /coins [get/post/delete/path/put]
  resources :coins

  # Redirect to welcome page/controller
  root to: 'welcome#index'

  get '/index', to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :switch_locale
    # if found the query param 'locale', it will change the translation
    # http://localhost:3000?locale=en
    def switch_locale
      cookies[:locale] = params[:locale] if params[:locale]
      return unless cookies[:locale]

      I18n.locale = cookies[:locale] if I18n.locale != cookies[:locale]
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[show edit update destroy]
  before_action :select_mining_type, only: %i[new edit update create]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show; end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit; end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def coin_params
    params.require(:coin).permit(:description, :acronym, :img_url, :mining_type_id)
  end

  def select_mining_type
     @select_mining_type_options = MiningType.all.pluck(:description, :id)
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[show edit update destroy]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show; end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit; end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mining_type
    @mining_type = MiningType.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mining_type_params
    params.require(:mining_type).permit(:description, :acronym)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_to_br(date = Date.today)
        date.strftime('%d/%m/%Y')
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h4>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= image_tag coin.img_url || '', width:35  %>
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field">
    <%= form.label :mining_type %>
    <%= form.select(:mining_type_id, @select_mining_type_options, {include_black: 'Select one option'}) %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h3>Editing Coin</h3>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Coins</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.img_url, width:35  %></td>                
        <td><%= link_to 'Show', coin %></td>
        <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h3>New Coin</h3>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>  
  <strong>Img url:</strong>
  <%= @coin.img_url %>
  <%= image_tag @coin.img_url, width:35  %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Wallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>    
  </head>

  <body class='container-fluid'>
    <header class=''>   
      <div class="row justify-content-md-center">
        <div class="col-1">
          <a href='/' >
            <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDAWT2U5O8J39bJcZrCZQR03gny3NFBq8oqsl1aAme3gcHN91tf5Z3A17toyH0itZV5gk&usqp=CAU', width:100  %>
          </a>
        </div>
        <div class="col-11">
          <h1 class="display-3"><%= I18n.t('header') %></h1>          
        </div>
      </div>  
      <div class="row">
        <div class="col-2">
          <p><strong><%= I18n.t('date-str') %>: </strong><%= I18n.l(Date.today) %></p>
        </div>
        <div class="col-2">
          <p><strong><%= I18n.t('language') %>: </strong><%= I18n.locale %></p>
        </div>
        <div class="col-8"></div>        
      </div>            
    </header>
    <hr />
    <main>
      <%= yield %>    
    </main>
    <hr />
    <footer>
        <p><%= I18n.t('environment') %>: <strong><%=Rails.env%></strong></p>
    </footer>    
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h4>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h3>Editing Mining Type</h3>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Mining Types</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to 'Show', mining_type %></td>
        <td><%= link_to 'Edit', edit_mining_type_path(mining_type) %></td>
        <td><%= link_to 'Destroy', mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mining Type', new_mining_type_path %>

app/views/mining_types/new.html.erb
<h3>New Mining Type</h3>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>

app/views/welcome/index.html.erb
<h3><%= I18n.t('welcome') %></h3>
<nav>
    <ul class='nav justify-content'>
        <li class='nav-item'>
            <%= link_to I18n.t('menu.add.coins'), coins_path, class: 'nav-link' %>
        </li>
        <li>
            <%= link_to I18n.t('menu.add.mining-types'), mining_types_path, class: 'nav-link' %>
        </li>    
    </ul>
</nav>